pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  branches:
    include: [ master, develop ]
  paths:
    include:
    - src/MindfulYoga.FunctionApp/*
    - src/MindfulYoga.Shared/*
    - src/MindfulYoga.Libraries/*

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .net core sdk
  inputs:
    version: '3.1.100'
    packageType: sdk

- script: dotnet tool restore
  displayName: 'Restore tools'

- script: dotnet fake build -t publishFunctionApp
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish App Artifacts'
  inputs:
    pathtoPublish: './deploy/functionApp'
    artifactName: 'functionApp'