name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.300

      - name: Install Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet fake build -t Publish

      - name: Publish Client
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: publish/client

      - name: Publish Server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: publish/functionApp
  deploy-client:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: client
          path: client
      - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: client
            CLEAN: true